language: cpp
addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-serialization-dev
script:
  - scons --keep-going checking=slow tests -j2
  - Tests/harness/unit-tests/unit-tests
  
